"""Generates documentation that must never disagree with its sources.

  docs/design-tokens.md   from design/library/tokens.json (values and computed contrast)
  docs/screen-specs.md    from a screen table below plus the FEAT specs (criteria and their TC ids)

Usage: python gen_docs.py            (run from anywhere; paths are relative to this file)
"""
import glob
import os
import re
import tokens_lib as tl

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))            # .assist/product-design
ASSIST = os.path.normpath(os.path.join(ROOT, ".."))          # .assist
TK = tl.load()


def wr(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


# ------------------------------------------------------------------ tokens
def tokens_doc():
    L = tl.resolve(TK, "light")
    D = tl.resolve(TK, "dark")
    rows = ""
    for name, spec in TK["semantic"].items():
        rows += f"| `{name}` | semantic | {spec['light'].split('color.')[1]} `{L[name]}` | {spec['dark'].split('color.')[1]} `{D[name]}` | {spec['use']} | stable |\n"
    prim = "".join(f"| `{n}` | primitive | `{val}` |\n" for n, val in TK["primitive"].items())
    mat = ""
    ok = 0
    for fg, bg, need, vals in tl.matrix(TK):
        passed = all(x >= need for x in vals)
        ok += passed
        mat += f"| `{fg}` on `{bg}` | {need}:1 | {vals[0]:.2f} | {vals[1]:.2f} | {'pass' if passed else 'FAIL'} |\n"
    typ = ""
    for n, s in TK["typography"].items():
        if n.startswith("type."):
            typ += f"| `{n}` | {TK['typography'][s['family']]} | {s['size']} / {s['line']} | {s['weight']} | {s['use']} |\n"
    sp = ", ".join(f"`{k}`" for k in TK["scale"]["space"])
    rad = ", ".join(f"`{k}` {v}" for k, v in TK["scale"]["radius"].items())
    dur = ", ".join(f"`{k}` {v} ms" for k, v in TK["scale"]["duration"].items())
    comp = "".join(f"| `{k}` | {v} |\n" for k, v in TK["component"].items())
    return f"""# Design tokens

Generated by `tools/gen_docs.py` from `design/library/tokens.json` (version {TK['version']}). **Do not edit by hand:** change the JSON, then regenerate. The `.pen` design files use the same JSON, and the Flutter theme must match it.

Direction: calm and minimal, warm neutral colours, one soft green accent, generous space. The journal text is the main content, so everything else stays quiet.

Modes: light and dark. High-contrast mode is not designed yet (open question in `context.md`).

## Tiers and naming
Three tiers (`design-token-authoring`): **primitive** (raw values), **semantic** (purpose, one value per mode), **component** (only where a component must differ from the semantic default). Screens use semantic or component tokens, never primitives. Names are lowercase and dot-separated, `category.property.role.variant`.

## Semantic colour tokens
| Token | Tier | Light | Dark | Use | Status |
|-------|------|-------|------|-----|--------|
{rows}
`color.border.default` is decorative only. Any control boundary uses `color.border.strong`, which meets 3:1.

## Contrast matrix (WCAG 2.2 AA, computed)
Text needs 4.5:1; control boundaries and focus rings need 3:1. {ok} of {len(tl.PAIRS)} pairs pass.

| Pair | Needed | Light | Dark | Result |
|------|--------|-------|------|--------|
{mat}
Disabled controls are exempt from the ratio but stay distinguishable by fill, border, and label. Colour never carries meaning alone: errors also have an icon and words, warnings have the word "Important", checked boxes have a tick.

## Typography
| Token | Font | Size / line height | Weight | Use |
|-------|------|--------------------|--------|-----|
{typ}
Both fonts are open source (SIL Open Font License) and may be bundled with the app; see `asset-register.md`. All sizes must scale with the system font size. The design previews cannot show every token faithfully (Lora is replaced by a fallback and Inter shows in one weight); `design-tokens.md` is the reference and the Flutter code implements it as written.

## Spacing, shape, motion, size
- Spacing scale: {sp}. Screen side margin {TK['scale']['screen']['margin']}.
- Radius: {rad}. Borders: hairline {TK['scale']['border']['hairline']} px, focus {TK['scale']['border']['focus']} px.
- Motion: {dur}. UI transitions stay at or under 300 ms and honour the system "reduce motion" setting. Screen design frame: {TK['scale']['screen']['width']} x {TK['scale']['screen']['height']}.
- No shadows: separation comes from surface colour and borders.

## Component tokens
| Token | Value |
|-------|-------|
{comp}
## Primitive tokens
| Token | Tier | Value |
|-------|------|-------|
{prim}
## Change process
A token change is proposed with name, reason, and affected components; classified patch (value tweak), minor (new token), or major (rename or removal); recorded in the changelog below; and announced to frontend-mobile with a migration note. Deleting a token is a breaking change (`design-system-governance`).

## Changelog
| Version | Date | Change |
|---------|------|--------|
| {TK['version']} | 2026-09-20 | Three tiers introduced; token names changed to `category.property.role`; new `color.border.strong` (3:1) because the old single border token measured about 1.4:1; new warning, pressed, focus, scrim tokens; contrast matrix computed. |
| 0.1.0 | 2026-09-20 | First flat token list (superseded). |
"""


# ------------------------------------------------------------------ screens
def spec_index():
    idx = {}
    for path in sorted(glob.glob(os.path.join(ASSIST, "product-manager", "features", "FEAT-*.md"))):
        t = open(path, encoding="utf-8").read()
        fid = re.search(r"^# (FEAT-\d{3})", t, re.M).group(1)
        for m in re.finditer(r"^\| (AC-\d+) \| (.*?) \| (.*?) \| (.*?) \| (TC-\d{3}) \|$", t, re.M):
            idx[(fid, m.group(1))] = (f"{m.group(2)}; {m.group(3)}; {m.group(4)}", m.group(5))
    return idx


A11Y_AC = [("Every control has a visible label or visible text, and an accessible name", "TC-087"), ("Text stays readable at 200 percent system font size in both themes", "TC-088"),
           ("Text contrast and touch targets meet the tokens in both themes", "TC-089")]

SCREENS = [
    dict(id="S1", name="Welcome", area="setup-and-lock", feat=["FEAT-004"], flow="F1", goal="Understand what the app is and start. Primary action: Get started. Secondary: Import your journal (restore path, order is a proposal).",
         states="Default; large text 200%", order="Title (heading), body, the three points (list), Get started, Import your journal. The logo is decorative and hidden from screen readers.",
         names="Logo: none (decorative). Buttons use their visible text.", edge="At 200% the content scrolls and the primary action is below the fold (finding N4). Translations up to 40% longer wrap. The three points never truncate.",
         acs=[("FEAT-004", [1])], oq="none: restore after passcode setup was decided on 2026-09-20."),
    dict(id="S2", name="Create passcode", area="setup-and-lock", feat=["FEAT-004"], flow="F1", goal="Choose a passcode the user can remember. Primary action: Continue.",
         states="Empty; valid; passcode shown; mismatch error; too easy error", order="Back, title (heading), body, Passcode label and field, Show or Hide, Repeat label and field, helper, Continue.",
         names="Back: \"Back\". Show and Hide: \"Show passcode\" and \"Hide passcode\". Fields are marked secure; errors are announced when they appear; paste is allowed so password managers work; copy out of the field is not.",
         edge="Continue is disabled until both fields are valid, with a sentence saying what is needed. Values the user typed are kept when an error appears. Validate on blur, then on change after the first error. The rule (at least 8 characters, not a very common passcode) is stated in the helper text and in the error.",
         acs=[("FEAT-004", [2, 3, 7])], oq="none: rules decided (`lock-and-passcode-policy`)."),
    dict(id="S3", name="Biometrics", area="setup-and-lock", feat=["FEAT-004", "FEAT-003"], flow="F1", goal="Offer a face or fingerprint shortcut. Primary action: Turn on. Secondary: Not now.",
         states="Available; not available", order="Back, title (heading), body, Turn on, Not now (or Continue when not available).", names="Buttons use their visible text.",
         edge="If nothing is set up on the phone, the screen says so and offers only Continue. The system prompt itself is drawn by the operating system, not by the app.", acs=[("FEAT-003", [4, 8])], oq="none"),
    dict(id="S4", name="No-recovery warning", area="setup-and-lock", feat=["FEAT-004"], flow="F1", goal="Make sure the user knows a forgotten passcode cannot be recovered. Primary action: Start journaling, enabled only after the box is ticked.",
         states="Not acknowledged; acknowledged", order="Back, title (heading), warning card (\"Important\" label, two sentences), acknowledgment checkbox row, helper, Start journaling.",
         names="Checkbox: the whole row is the control (56 high), named by its sentence. The card is a group named \"Important\".",
         edge="The disabled button is explained by the sentence \"Tick the box to continue.\". Warning meaning is carried by the word \"Important\" and the text, not by colour.",
         acs=[("FEAT-004", [4, 5, 6])], oq="none"),
    dict(id="S5", name="Lock screen", area="setup-and-lock", feat=["FEAT-003"], flow="F2", goal="Unlock the journal. Primary action: Unlock. Secondary: Use face or fingerprint.",
         states="Default; wrong passcode; waiting after wrong tries; app-switcher preview; large text 200%", order="Title, Passcode label and field, Unlock, Use face or fingerprint.",
         names="The countdown is announced once when the wait starts and again when it ends, not every second. The wrong-passcode message is announced when it appears.",
         edge="No journal content is shown in any lock state, including the app-switcher preview (blank and branded). After the fifth wrong passcode the first wait is 30 seconds and doubles up to one hour; the countdown is the screen's only change. On Android screenshots are blocked.",
         acs=[("FEAT-003", [1, 2, 3, 4, 5, 6, 7, 9, 10, 11])], oq="none: wait, timeout, and screenshot rules decided (`lock-and-passcode-policy`)."),
    dict(id="S6", name="Timeline", area="journal", feat=["FEAT-002", "FEAT-008"], flow="F3, F7", goal="Browse entries and start a new one. Primary action: New entry.",
         states="Entries; with backup reminder; empty (first use); loading; large text 200%", order="Title (heading), Settings, search field, reminder banner (when shown), day headings and entries, New entry.",
         names="Each entry row reads its time, then its preview text. Search field: \"Search your entries\". Reminder actions: \"Export now\" and \"Later\".",
         edge="Empty and loading are different states. The reminder never contains entry text. At 200% the header stacks and the New entry button grows with its text.",
         acs=[("FEAT-002", [1, 2, 3, 4, 5]), ("FEAT-008", [1, 2, 3, 4, 5, 6])], oq="none: reminder after more than 30 days, hidden for 7 days; journal size 20,000 entries."),
    dict(id="S7", name="Editor", area="journal", feat=["FEAT-001"], flow="F3", goal="Write or change an entry safely. Primary action: Save.",
         states="New; editing; long entry; delete confirmation; resume unsaved draft; save error; large text 200%", order="Back, date, Save, draft status, entry text, Delete entry (existing entries only).",
         names="Entry text area: \"Entry text\". Date: \"Entry date, Saturday 20 September 2026, change\". Delete sheet and draft dialog are announced as dialogs.",
         edge="The draft is kept as the user types, so leaving the screen never loses text. The save error keeps the text and offers Try again. The \"Save\" action next to \"Draft kept safely\" is tested for confusion in RS-001.",
         acs=[("FEAT-001", [1, 2, 3, 4, 5, 6, 7, 8])], oq="none: no artificial maximum length; the open-failure state is S14."),
    dict(id="S8", name="Search", area="journal", feat=["FEAT-005"], flow="F4", goal="Find an old entry by a word. Primary action: type a word.",
         states="Empty query; results; no results", order="Back, search field, result count, results.", names="Search field: \"Search your entries\". Result rows name their date and matched word.",
         edge="Query and results are kept when returning from an entry. The matched word is shown in a note because inline highlighting cannot be drawn in the design tool.",
         acs=[("FEAT-005", [1, 2, 3, 4, 5, 6, 7, 8])], oq="none: matching rules decided."),
    dict(id="S9", name="Settings", area="backup-and-settings", feat=["FEAT-009"], flow="F5, F6", goal="Change appearance and security, and reach export and import.",
         states="Default; language choice; lock timeout choice", order="Back, title, Appearance (Theme, Language), Security, Backup, About; each row reads its label then its value.", names="Switch: \"Face or fingerprint, on\". Rows with a chevron are buttons that open a screen or a choice sheet. Language choices are announced in their own language.",
         edge="Row values wrap under their label at large text. The language default follows the phone, and English is used when the phone is neither English nor Indonesian. The lock timeout default is Immediately.", acs=[("FEAT-009", [1, 5, 6, 8, 9])], oq="none."),
    dict(id="S10", name="Change passcode", area="backup-and-settings", feat=["FEAT-009"], flow="F1", goal="Change the passcode without losing access. Primary action: Change passcode.",
         states="Default; wrong current passcode; passcodes differ; done", order="Back, title, Current passcode, New passcode, Repeat new passcode, Change passcode.",
         names="Same secure-field rules as S2.", edge="A change that is interrupted must leave the journal openable (TC-082).", acs=[("FEAT-009", [2, 3, 4])], oq="none: same passcode rules as setup."),
    dict(id="S11", name="Export", area="backup-and-settings", feat=["FEAT-006"], flow="F5", goal="Make a backup file. Primary action: Continue, then Export.",
         states="Choose; set password; readable-by-anyone warning; working; done; error", order="Back, title, options, Continue; then password fields, Export; then progress with Cancel.",
         names="Options are radio buttons named by their title and description. The progress bar reads its caption, updated at intervals, not continuously.",
         edge="The password step says the export password is not the passcode and cannot be recovered. The warning names the consequence before the destructive-styled button. An error keeps the last export time unchanged.",
         acs=[("FEAT-006", [1, 2, 3, 4, 5, 6, 7, 8, 9])], oq="Vocabulary Export versus Back up is tested in RS-001."),
    dict(id="S12", name="Import", area="backup-and-settings", feat=["FEAT-007"], flow="F6", goal="Restore a journal from an export. Primary action: Choose a file, then Import.",
         states="Choose file; password; wrong password; working; result; damaged file; newer version; wrong file", order="Back, title, body, Choose a file; then password field, Import; then progress, Cancel; then result.",
         names="Errors are announced when they appear and always say that nothing was changed.", edge="Every error path ends in a defined state and leaves the journal unchanged. The counts in the result are illustrative.",
         acs=[("FEAT-007", [1, 2, 3, 4, 5, 6, 7, 8, 9])], oq="none: merge rule and restore order decided."),
    dict(id="S13", name="About and privacy", area="backup-and-settings", feat=["FEAT-009"], flow="none", goal="State plainly what the app does and does not do with data.",
         states="Default", order="Back, title (heading), four points (list).", names="The points form a list.",
         edge="Every claim must trace to a requirement and a test (TC-081); a claim with no control behind it is removed.", acs=[("FEAT-009", [7])], oq="Indonesian text of the statement is reviewed by the owner."),
    dict(id="S14", name="Journal cannot be opened", area="setup-and-lock", feat=["FEAT-001"], flow="none (new)", goal="Recover when the journal cannot be opened (for example damaged data). Primary action: Try again.",
         states="Error", order="Title, body, Try again, Import your journal.", names="The message is announced on arrival.",
         edge="Nothing has been deleted, and the screen says so. It is also shown after a failed data migration once the journal has been restored (ADR-006). The behaviour was decided on 2026-09-20 and is FEAT-001 AC-9.",
         acs=[("FEAT-001", [9, 10, 11])], oq="none."),
]


def screens_doc():
    idx = spec_index()
    out = ["""# Screen design specs (version 1)

Generated by `tools/gen_docs.py` from the screen table in that script and the acceptance criteria in the FEAT specs. Design files: `design/features/<area>/<area>-light.pen` and `-dark.pen`, exported previews in `design/exports/`. Tokens: `design-tokens.md`. Components: `component-specs.md`. Flows: `../../ux-design/report/user-flows.md`.

Status: draft, owner product-design, tokens 0.2.0. Every screen is drawn in every state listed. Screens are 390 x 844 (compact phone); tablets and landscape are not designed for version 1. Copy is draft and all strings must be externalised for translation. Numbers, dates, and counts on screen are illustrative.

Common to every screen: safe areas respected; primary action reachable by one thumb; all touch targets at least 48; error text always says what happened and what to do next; layout stays stable while loading; motion at most 300 ms and off under "reduce motion". Screens have no analytics events: the app collects none.
"""]
    for s in SCREENS:
        rows = ""
        n = 0
        for feat, acs in s["acs"]:
            for a in acs:
                crit, tc = idx.get((feat, f"AC-{a}"), ("(criterion not found)", "none"))
                n += 1
                rows += f"| AC-{n} | {crit} | {feat} AC-{a} | {tc} |\n"
        for crit, tc in A11Y_AC:
            n += 1
            rows += f"| AC-{n} | {crit} | design | {tc} |\n"
        if not s["acs"]:
            rows = "| none | No acceptance criterion exists for this state yet | none | none |\n" + rows
        out.append(f"""
## {s['id']} {s['name']}

| Field | Value |
|-------|-------|
| Screen | {s['id']} {s['name']} |
| Feature | {', '.join(s['feat']) if s['feat'] else 'none yet (see edge cases)'} |
| Status | draft |
| Design file | `design/features/{s['area']}/{s['area']}-light.pen` and `-dark.pen` |
| Flow context | {s['flow']} in `ux-design/report/user-flows.md` |

**Goal.** {s['goal']}

**States drawn.** {s['states']}.

**Reading and focus order.** {s['order']}

**Accessible names and announcements.** {s['names']}

**Edge cases.** {s['edge']}

**Open questions.** {s['oq']}

| AC | Criterion | Source | Test |
|----|-----------|--------|------|
{rows}""")
    return "".join(out)


if __name__ == "__main__":
    wr(os.path.join(ROOT, "docs", "design-tokens.md"), tokens_doc())
    wr(os.path.join(ROOT, "docs", "screen-specs.md"), screens_doc())
    print("docs written")
